### ISSUE TITLE
Get Rob--W on his own repo

### ISSUE THREAD

**Issue by rclai** [proxv/node-xvfb#3]
@Rob--W are you able to create your xvfb module on a new GH repo? I have some questions about its usage.

**Comment by Rob--W** [comment]
It is here: https://github.com/Rob--W/node-xvfb

**Comment by rclai** [comment]
I cannot submit issues there because it is a fork.

**Comment by Rob--W** [comment]
I've now enabled issues for the repo. It is apparently disabled by default for forks. Thanks for letting me know!

**Comment by rclai** [comment]
Okay cool, thanks.
